### ISSUE TITLE
Null Werte ignorieren

### ISSUE THREAD

**Issue by Ricox1975** [BenAhrdt/ioBroker.drag-indicator#4]
Ich tracke die Kraftstoffpreise über Tankerkönig. Hier wird bei Minimum immer 0€ ausgegeben.

**Comment by BenAhrdt** [comment]
Aktuelle Version?
Glaube es liegt am init. trag doch bitte einfach mal bei min einen hohen Wert ein und schaue ob er überschrieben wird

**Comment by BenAhrdt** [comment]
@Ricox1975 Kannst Dir mal die aktuelle Version installieren.
Erzeugte states in der instanz vor dem starten löschen, dann sollte der aktuelle wert gezogen werden.
